version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "daily"
    labels: ["infrastructure", "dependencies"]
    commit-message:
      prefix: "[#1234] "
    pull-request-branch-name:
      prefix: "iox2-1234-"
      separator: "-"

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"
  - package-ecosystem: "bazel"
    directories:
      - "/"
      - "/examples/bazel/*"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"
  - package-ecosystem: "pip"
    directories: 
      - "/iceoryx2-ffi/python"
      - "/doc/api/python"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"
